version: '3'

services:
  # Django web application
  web:
    container_name: django-nginx-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    # depends_on:
    #   - db
    environment:
      - DEBUG=True  # Set your Django application environment variables here
    command: sh ./entrypoint.sh

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./:/code
      - certbot:/etc/letsencrypt
      - certbot:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - certbot:/etc/letsencrypt
      - certbot:/var/www/certbot
    depends_on:
      - web
    command: certonly --webroot -w /var/www/certbot --force-renewal --email email@gmail.com -d acmetrading.org --agree-tos

  # # PostgreSQL database
  # db:
  #   image: postgres:14.1-alpine
  #   container_name: my-postgres-db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #         - "5432:5432"
  #   env_file:
  #     - .env # Include the environment file here

volumes:
  # postgres_data:
  static:
  certbot:
